# Use postgres/example user/password credentials
version: '3'

services:

  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: test123
    ports:
      - 5432:5432

  mongo:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - ./db-data:/data/db
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: test123
